name: Wayne La Photographer
favicon: null
layout_spectrum: 0.74459
typography_spectrum: 0.49706
title: 'Wayne La ~ London Photographer | Portrait | Street | Wedding Reportage | Fuji-X.'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#f6f6f6'
    - '#525252'
    - '#747474'
    - '#b4b4b4'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
