name: Wayne La Photographer
favicon: null
layout_spectrum: 0.39132
typography_spectrum: 0.2141
title: 'Wayne La ~ London Photographer | Portrait | Street | Wedding Reportage | Fuji-X.'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000d17'
    - '#f4f6f5'
    - '#5c8186'
    - '#00577d'
    - '#c2bb82'
  brandStrength: 0.1875
  lightness: 0.375
  saturation: 0.75
  rhythmicContrast: 0.25
purpose: []
