typography_spectrum: 0.2141
color:
  brandColors:
    - '#000000'
    - '#686868'
    - '#363636'
    - '#a9a9a9'
    - '#eeeeee'
  brandStrength: 0.6875
  lightness: 0.5
  saturation: 0.6875
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.39132
analytics:
  google: null
  facebook: null
  twitter: null
name: Wayne La Photographer
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Wayne La ~ London Photographer | Portrait | Street | Fuji-X.
purpose: []
